darcsum notes

* backlog
** release 1.3
*** update site
**** update for current hakyll
*** clarify maintainer, repo
** errors
*** changes containing non-ascii characters do not take effect
*** darcsum-ediff, darcsum-diff fail in hashed repo without vc-darcs.
*** darcsum-query-manifest: darcs failed:  unrecognized option
   `--quiet'

** wishes
*** don't hang on unexpected darcs output
Symptoms: the darcsum buffer fails to update within the expected time,
the next operation fails due to _darcs/lock still present, the darcs
process is found to be still running but idle.

Workaround: kill the process manually, also remove the lock file if
needed, and repeat the operation with darcsum-debug enabled to see
what caused the problem.

Cause: using the process-filter mechanism to drive an interactive
darcs session is fragile. Because data is received in random chunks it
can't reliably distinguish incomplete data and data it can't parse.

*** magit-style log, push, pull
*** ELPA package
*** handle darcs setpref
*** hunk splitting (e)
*** When merging changesets, check the content of change text too
*** Better support for moving files
*** use --interactive with apply, for applying patches from e-mail via darcsum
*** Better logfile handling
This should use vc-darcs but it's non-trivial to get it invoked
appropriately in Emacs 21, 22, and 23.
*** Interface to darcs replace, unrecord, mv, tag, pull, ...
* unused site bits
    <link rel="stylesheet" type="text/css" href="$root/style.css" />
    <div id="footer">
      <hr />
      &copy; 2007-2010 <a href="http://joyful.com/">Simon Michael</a> and contributors
    </div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("");
pageTracker._trackPageview();
} catch(err) {}
</script>

