
;;
;; file: green-hell-mac.el
;;

(defun sweyla779450 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/779450/"
  (interactive)
  (color-theme-install
   '(sweyla779450
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#A4FFAA"))))
     (font-lock-constant-face ((t (:foreground "#FFCC84"))))
     (font-lock-builtin-face ((t (:foreground "#FFA8A1"))))
     (font-lock-function-name-face ((t (:foreground "#FFFF5F"))))
     (font-lock-variable-name-face ((t (:foreground "#FFFFD5"))))
     (font-lock-keyword-face ((t (:foreground "#B1E56E"))))
     (font-lock-string-face ((t (:foreground "#B8D88C"))))
     (font-lock-doc-string-face ((t (:foreground "#B8D88C"))))
     (font-lock-type-face ((t (:foreground "#DFFF87"))))
     )))

(provide 'sweyla779450)
