;;
;; ------[ Crshd2 Theme ]-------
;;

(deftheme crshd2
  "strange, darkish colors")

(let ((class '((class color) (min-colors 89)))
      ;; color definitions
      ;; colors with +x are lighter, colors with -x are darker
      (crshd2-fg   "#c7c7c7")

      (crshd2-bg-1 "#393939")
      (crshd2-bg   "#151515")
      (crshd2-bg+1 "#151515")
      (crshd2-bg+2 "#474747")

      (crshd2-red+1 "#ff9f95")
      (crshd2-red   "#ff9f95")
      (crshd2-red-1 "#ff8d80")
      (crshd2-red-2 "#ff8d80")
      (crshd2-red-3 "#ff8d80")

      (crshd2-orange "#e2b5cc")

      (crshd2-yellow   "#ffbe64")
      (crshd2-yellow-1 "#ffffb9")
      (crshd2-yellow-2 "#ffffb9")

      (crshd2-green-1 "#e2ffc7")
      (crshd2-green   "#e2ffc7")
      (crshd2-green+1 "#d8ffb3")
      (crshd2-green+2 "#d8ffb3")
      (crshd2-green+3 "#d8ffb3")
      (crshd2-green+4 "#d8ffb3")

      (crshd2-cyan "#9ce9ff")

      (crshd2-blue+1 "#a8ceea")
      (crshd2-blue   "#a8ceea")
      (crshd2-blue-1 "#7eb6ff")
      (crshd2-blue-2 "#7eb6ff")
      (crshd2-blue-3 "#7eb6ff")
      (crshd2-blue-4 "#7eb6ff")
      (crshd2-blue-5 "#7eb6ff")

      (crshd2-magenta "#e296ff"))

  (custom-theme-set-faces
   'crshd2

   ;;; basic coloring
   (set-frame-parameter (selected-frame) 'internal-border-width 15)
   
   `(default ((,class (:foreground ,crshd2-fg 
								   :background ,crshd2-bg 
								   :height 100
								   :family "Inconsolata"))))
   `(cursor ((,class (:foreground ,crshd2-fg))))
   `(fringe ((,class (:foreground ,crshd2-cyan :background ,crshd2-bg-1))))
   `(escape-glyph-face ((,class (:foreground ,crshd2-red))))
   `(header-line ((,class (:foreground ,crshd2-yellow
:background ,crshd2-bg-1
:box (:line-width 1 :color ,crshd2-bg-1)))))
   `(hl-line ((,class (:background ,crshd2-bg+1))))
   `(linum ((,class (:foreground "#505050" :background ,crshd2-bg-1))))
   `(minibuffer-prompt ((,class (:foreground ,crshd2-yellow))))
   `(menu ((,class (:foreground ,crshd2-fg :background ,crshd2-bg))))
   `(mode-line
     ((,class (:foreground ,crshd2-fg :background ,crshd2-bg+1
:box (:line-width 1 :color ,crshd2-bg+1)))))
   `(mode-line-inactive ((,class (:inherit mode-line :background ,crshd2-bg+2
:box (:line-width 1 :color ,crshd2-bg-1)))))
   `(mode-line-buffer-id ((,class (:inherit 'crshd2-yellow :weight bold))))
   `(mode-line-inactive
     ((,class (:foreground ,crshd2-green-1 :background ,crshd2-bg+1))))
   `(mode-line-buffer-name ((,class (:foreground ,crshd2-green :weight bold))))
   `(mode-line-mode-face ((,class (:foreground ,crshd2-yellow))))
   `(mode-line-folder-face ((,class (:foreground ,crshd2-bg+2))))
   `(mode-line-modified-face ((,class (:foreground ,crshd2-orange :background ,crshd2-bg+1))))
   `(mode-line-read-only-face ((,class (:foreground ,crshd2-red))))
   `(region ((,class (:background ,crshd2-bg+2))))
   `(secondary-selection ((,class (:background ,crshd2-bg+2))))
   `(trailing-whitespace ((,class (:background ,crshd2-red))))
   `(vertical-border ((,class (:foreground ,crshd2-fg))))

   ;; faces used by isearch
   `(isearch ((,class (:foreground ,crshd2-yellow :background ,crshd2-bg-1))))
   `(isearch-fail ((,class (:foreground ,crshd2-fg :background ,crshd2-red-3))))
   `(lazy-highlight ((,class (:foreground ,crshd2-yellow :background ,crshd2-bg+2))))

   ;; font-lock
   `(font-lock-builtin-face ((,class (:foreground ,crshd2-blue))))
   `(font-lock-comment-face ((,class (:foreground ,crshd2-bg+2))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,crshd2-bg+2))))
   `(font-lock-constant-face ((,class (:foreground ,crshd2-fg))))
   `(font-lock-doc-face ((,class (:foreground ,crshd2-green+1))))
   `(font-lock-doc-string-face ((,class (:foreground ,crshd2-blue+1))))
   `(font-lock-function-name-face ((,class (:foreground ,crshd2-blue))))
   `(font-lock-keyword-face ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(font-lock-negation-char-face ((,class (:foregorund ,crshd2-fg))))
   `(font-lock-preprocessor-face ((,class (:foreground ,crshd2-blue))))
   `(font-lock-string-face ((,class (:foreground ,crshd2-red))))
   `(font-lock-type-face ((,class (:foregorund ,crshd2-yellow))))
   `(font-lock-variable-name-face ((,class (:foreground ,crshd2-yellow))))
   `(font-lock-warning-face ((,class (:foreground ,crshd2-yellow-1 :weight bold :underline t))))
   `(font-lock-pseudo-keyword-face ((,class (:foreground ,crshd2-yellow))))
   `(font-lock-operator-face ((,class (:foreground ,crshd2-orange))))

   `(c-annotation-face ((,class (:inherit font-lock-constant-face))))

   ;;; external

   ;; auto-complete
   `(ac-candidate-face ((,class (:background ,crshd2-bg+2 :foreground "white"))))
   `(ac-selection-face ((,class (:background ,crshd2-blue-4 :foreground ,crshd2-fg))))
   `(popup-tip-face ((,class (:background ,crshd2-yellow-2 :foreground "black"))))
   `(popup-scroll-bar-foreground-face ((,class (:background "white"))))
   `(popup-scroll-bar-background-face ((,class (:background ,crshd2-bg-1))))
   `(popup-isearch-match ((,class (:background ,crshd2-bg :foreground ,crshd2-fg))))

   ;; diff
   `(diff-added ((,class (:foreground ,crshd2-green+4))))
   `(diff-changed ((,class (:foreground ,crshd2-yellow))))
   `(diff-removed ((,class (:foreground ,crshd2-red))))
   `(diff-header ((,class (:background ,crshd2-bg+1))))
   `(diff-file-header
     ((,class (:background ,crshd2-bg+2 :foreground ,crshd2-fg :bold t))))

   ;; eshell
   `(eshell-prompt ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(eshell-ls-archive ((,class (:foreground ,crshd2-red-1 :weight bold))))
   `(eshell-ls-backup ((,class (:inherit font-lock-comment))))
   `(eshell-ls-clutter ((,class (:inherit font-lock-comment))))
   `(eshell-ls-directory ((,class (:foreground ,crshd2-blue+1 :weight bold))))
   `(eshell-ls-executable ((,class (:foreground ,crshd2-red+1 :weight bold))))
   `(eshell-ls-unreadable ((,class (:foreground ,crshd2-fg))))
   `(eshell-ls-missing ((,class (:inherit font-lock-warning))))
   `(eshell-ls-product ((,class (:inherit font-lock-doc))))
   `(eshell-ls-special ((,class (:inherit crshd2-yellow :weight bold))))
   `(eshell-ls-symlink ((,class (:foreground ,crshd2-cyan :weight bold))))

   ;; ecb
   `(ecb-analyse-bucket-element-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-analyse-bucket-node-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-analyse-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-analyse-general-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-bucket-node-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-default-general-face ((,class (:inherit crshd2-fg))))
   `(ecb-default-highlight-face ((,class (:foreground ,crshd2-green :background ,crshd2-bg :weight bold))))
   `(ecb-directories-general-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-directory-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-directory-not-accessible-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-history-bucket-node-dir-soure-path-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-history-bucket-node-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-history-dead-buffer-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-history-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-history-general-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-history-indirect-buffer-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-method-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-method-non-semantic-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-methods-general-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-mode-line-data-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-mode-line-prefix-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-mode-line-win-nr-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-source-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-source-in-directories-buffer-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-source-read-only-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-sources-general-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-symboldef-prototype-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-symboldef-symbol-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-tag-header-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-tree-guide-line-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-type-tag-class-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-type-tag-enum-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-type-tag-group-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-type-tag-interface-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-type-tag-struct-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(ecb-type-tag-typedef-face ((,class (:foreground ,crshd2-cyan :weight bold))))

   ;; erc
   `(erc-action-face ((,class (:inherit erc-default-face))))
   `(erc-bold-face ((,class (:weight bold))))
   `(erc-current-nick-face ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(erc-dangerous-host-face ((,class (:inherit font-lock-warning))))
   `(erc-default-face ((,class (:foreground ,crshd2-fg))))
   `(erc-direct-msg-face ((,class (:inherit erc-default))))
   `(erc-error-face ((,class (:inherit font-lock-warning))))
   `(erc-fool-face ((,class (:inherit erc-default))))
   `(erc-highlight-face ((,class (:inherit hover-highlight))))
   `(erc-input-face ((,class (:foreground ,crshd2-yellow))))
   `(erc-keyword-face ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(erc-nick-default-face ((,class (:weight bold))))
   `(erc-nick-msg-face ((,class (:inherit erc-default))))
   `(erc-notice-face ((,class (:foreground ,crshd2-green))))
   `(erc-pal-face ((,class (:foreground ,crshd2-orange :weight bold))))
   `(erc-prompt-face ((,class (:foreground ,crshd2-orange :weight bold))))
   `(erc-timestamp-face ((,class (:foreground ,crshd2-green+1))))
   `(erc-underline-face ((t (:underline t))))

   ;; evil
   `(evil-state-face ((,class (:foreground ,crshd2-bg-1 :background ,crshd2-green :weight bold :box (:line-width 4 :color ,crshd2-green)))))
   ;; flymake
   `(flymake-errline ((,class (:foreground ,crshd2-red-1 :weight bold :underline t))))
   `(flymake-warnline ((,class (:foreground ,crshd2-yellow-1 :weight bold :underline t))))

   ;; flyspell
   `(flyspell-duplicate ((,class (:foreground ,crshd2-yellow-1 :weight bold :underline t))))
   `(flyspell-incorrect ((,class (:foreground ,crshd2-red-1 :weight bold :underline t))))

   ;; gnus
   `(gnus-group-mail-1-face ((,class (:bold t :inherit gnus-group-mail-1-empty))))
   `(gnus-group-mail-1-empty-face ((,class (:inherit gnus-group-news-1-empty))))
   `(gnus-group-mail-2-face ((,class (:bold t :inherit gnus-group-mail-2-empty))))
   `(gnus-group-mail-2-empty-face ((,class (:inherit gnus-group-news-2-empty))))
   `(gnus-group-mail-3-face ((,class (:bold t :inherit 'nus-group-mail-3-empty))))
   `(gnus-group-mail-3-empty-face ((,class (:inherit gnus-group-news-3-empty))))
   `(gnus-group-mail-4-face ((,class (:bold t :inherit gnus-group-mail-4-empty))))
   `(gnus-group-mail-4-empty-face ((,class (:inherit gnus-group-news-4-empty))))
   `(gnus-group-mail-5-face ((,class (:bold t :inherit gnus-group-mail-5-empty))))
   `(gnus-group-mail-5-empty-face ((,class (:inherit gnus-group-news-5-empty))))
   `(gnus-group-mail-6-face ((,class (:bold t :inherit gnus-group-mail-6-empty))))
   `(gnus-group-mail-6-empty-face ((,class (:inherit gnus-group-news-6-empty))))
   `(gnus-group-mail-low-face ((,class (:bold t :inherit gnus-group-mail-low-empty))))
   `(gnus-group-mail-low-empty-face ((,class (:inherit gnus-group-news-low-empty))))
   `(gnus-group-news-1-face ((,class (:bold t :inherit gnus-group-news-1-empty))))
   `(gnus-group-news-2-face ((,class (:bold t :inherit gnus-group-news-2-empty))))
   `(gnus-group-news-3-face ((,class (:bold t :inherit gnus-group-news-3-empty))))
   `(gnus-group-news-4-face ((,class (:bold t :inherit gnus-group-news-4-empty))))
   `(gnus-group-news-5-face ((,class (:bold t :inherit gnus-group-news-5-empty))))
   `(gnus-group-news-6-face ((,class (:bold t :inherit gnus-group-news-6-empty))))
   `(gnus-group-news-low-face ((,class (:bold t :inherit gnus-group-news-low-empty))))
   `(gnus-header-content-face ((,class (:inherit message-header-other))))
   `(gnus-header-from-face ((,class (:inherit message-header-from))))
   `(gnus-header-name-face ((,class (:inherit message-header-name))))
   `(gnus-header-newsgroups-face ((,class (:inherit message-header-other))))
   `(gnus-header-subject-face ((,class (:inherit message-header-subject))))
   `(gnus-summary-cancelled-face ((,class (:foreground ,crshd2-orange))))
   `(gnus-summary-high-ancient-face ((,class (:foreground ,crshd2-blue))))
   `(gnus-summary-high-read-face ((,class (:foreground ,crshd2-green :weight bold))))
   `(gnus-summary-high-ticked-face ((,class (:foreground ,crshd2-orange :weight bold))))
   `(gnus-summary-high-unread-face ((,class (:foreground ,crshd2-fg :weight bold))))
   `(gnus-summary-low-ancient-face ((,class (:foreground ,crshd2-blue))))
   `(gnus-summary-low-read-face ((,class (:foreground ,crshd2-green))))
   `(gnus-summary-low-ticked-face ((,class (:foreground ,crshd2-orange :weight bold))))
   `(gnus-summary-low-unread-face ((,class (:foreground ,crshd2-fg))))
   `(gnus-summary-normal-ancient-face ((,class (:foreground ,crshd2-blue))))
   `(gnus-summary-normal-read-face ((,class (:foreground ,crshd2-green))))
   `(gnus-summary-normal-ticked-face ((,class (:foreground ,crshd2-orange :weight bold))))
   `(gnus-summary-normal-unread-face ((,class (:foreground ,crshd2-fg))))
   `(gnus-summary-selected-face ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(gnus-cite-1-face ((,class (:foreground ,crshd2-blue))))
   `(gnus-cite-10-face ((,class (:foreground ,crshd2-yellow-1))))
   `(gnus-cite-11-face ((,class (:foreground ,crshd2-yellow))))
   `(gnus-cite-2-face ((,class (:foreground ,crshd2-blue-1))))
   `(gnus-cite-3-face ((,class (:foreground ,crshd2-blue-2))))
   `(gnus-cite-4-face ((,class (:foreground ,crshd2-green+2))))
   `(gnus-cite-5-face ((,class (:foreground ,crshd2-green+1))))
   `(gnus-cite-6-face ((,class (:foreground ,crshd2-green))))
   `(gnus-cite-7-face ((,class (:foreground ,crshd2-red))))
   `(gnus-cite-8-face ((,class (:foreground ,crshd2-red-1))))
   `(gnus-cite-9-face ((,class (:foreground ,crshd2-red-2))))
   `(gnus-group-news-1-empty-face ((,class (:foreground ,crshd2-yellow))))
   `(gnus-group-news-2-empty-face ((,class (:foreground ,crshd2-green+3))))
   `(gnus-group-news-3-empty-face ((,class (:foreground ,crshd2-green+1))))
   `(gnus-group-news-4-empty-face ((,class (:foreground ,crshd2-blue-2))))
   `(gnus-group-news-5-empty-face ((,class (:foreground ,crshd2-blue-3))))
   `(gnus-group-news-6-empty-face ((,class (:foreground ,crshd2-bg+2))))
   `(gnus-group-news-low-empty-face ((,class (:foreground ,crshd2-bg+2))))
   `(gnus-signature-face ((,class (:foreground ,crshd2-yellow))))
   `(gnus-x-face ((,class (:background ,crshd2-fg :foreground ,crshd2-bg))))

   ;; magit
   `(magit-section-title ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(magit-branch ((,class (:foreground ,crshd2-orange :weight bold))))

   ;; message-mode
   `(message-cited-text-face ((,class (:inherit font-lock-comment))))
   `(message-header-name-face ((,class (:foreground ,crshd2-green+1))))
   `(message-header-other-face ((,class (:foreground ,crshd2-green))))
   `(message-header-to-face ((,class (:inherit 'crshd2-yellow :weight bold))))
   `(message-header-from-face ((,class (:inherit 'crshd2-yellow :weight bold))))
   `(message-header-cc-face ((,class (:inherit 'crshd2-yellow :weight bold))))
   `(message-header-newsgroups-face ((,class (:inherit 'crshd2-yellow :weight bold))))
   `(message-header-subject-face ((,class (:inherit 'crshd2-orange :weight bold))))
   `(message-header-xheader-face ((,class (:foreground ,crshd2-green))))
   `(message-mml-face ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(message-separator-face ((,class (:inherit font-lock-comment))))

   ;; mew
   `(mew-face-header-subject ((,class (:foreground ,crshd2-orange))))
   `(mew-face-header-from ((,class (:foreground ,crshd2-yellow))))
   `(mew-face-header-date ((,class (:foreground ,crshd2-green))))
   `(mew-face-header-to ((,class (:foreground ,crshd2-red))))
   `(mew-face-header-key ((,class (:foreground ,crshd2-green))))
   `(mew-face-header-private ((,class (:foreground ,crshd2-green))))
   `(mew-face-header-important ((,class (:foreground ,crshd2-blue))))
   `(mew-face-header-marginal ((,class (:foreground ,crshd2-fg :weight bold))))
   `(mew-face-header-warning ((,class (:foreground ,crshd2-red))))
   `(mew-face-header-xmew ((,class (:foreground ,crshd2-green))))
   `(mew-face-header-xmew-bad ((,class (:foreground ,crshd2-red))))
   `(mew-face-body-url ((,class (:foreground ,crshd2-orange))))
   `(mew-face-body-comment ((,class (:foreground ,crshd2-fg :slant italic))))
   `(mew-face-body-cite1 ((,class (:foreground ,crshd2-green))))
   `(mew-face-body-cite2 ((,class (:foreground ,crshd2-blue))))
   `(mew-face-body-cite3 ((,class (:foreground ,crshd2-orange))))
   `(mew-face-body-cite4 ((,class (:foreground ,crshd2-yellow))))
   `(mew-face-body-cite5 ((,class (:foreground ,crshd2-red))))
   `(mew-face-mark-review ((,class (:foreground ,crshd2-blue))))
   `(mew-face-mark-escape ((,class (:foreground ,crshd2-green))))
   `(mew-face-mark-delete ((,class (:foreground ,crshd2-red))))
   `(mew-face-mark-unlink ((,class (:foreground ,crshd2-yellow))))
   `(mew-face-mark-refile ((,class (:foreground ,crshd2-green))))
   `(mew-face-mark-unread ((,class (:foreground ,crshd2-red-2))))
   `(mew-face-eof-message ((,class (:foreground ,crshd2-green))))
   `(mew-face-eof-part ((,class (:foreground ,crshd2-yellow))))

   ;; nav
   `(nav-face-heading ((,class (:foreground ,crshd2-yellow))))
   `(nav-face-button-num ((,class (:foreground ,crshd2-cyan))))
   `(nav-face-dir ((,class (:foreground ,crshd2-green))))
   `(nav-face-hdir ((,class (:foreground ,crshd2-red))))
   `(nav-face-file ((,class (:foreground ,crshd2-fg))))
   `(nav-face-hfile ((,class (:foreground ,crshd2-red-3))))

   ;; org-mode
   `(org-agenda-date-today
     ((,class (:foreground "white" :slant italic :weight bold))) t)
   `(org-agenda-structure
     ((,class (:inherit font-lock-comment-face))))
   `(org-archived ((,class (:foreground ,crshd2-fg :weight bold))))
   `(org-checkbox ((,class (:background ,crshd2-bg+2 :foreground "white"
:box (:line-width 1 :style released-button)))))
   `(org-date ((,class (:foreground ,crshd2-blue :underline t))))
   `(org-deadline-announce ((,class (:foreground ,crshd2-red-1))))
   `(org-done ((,class (:bold t :weight bold :foreground ,crshd2-green+3))))
   `(org-formula ((,class (:foreground ,crshd2-yellow-2))))
   `(org-headline-done ((,class (:foreground ,crshd2-green+3))))
   `(org-hide ((,class (:foreground ,crshd2-bg-1))))
   `(org-level-1 ((,class (:foreground ,crshd2-orange))))
   `(org-level-2 ((,class (:foreground ,crshd2-green+1))))
   `(org-level-3 ((,class (:foreground ,crshd2-blue-1))))
   `(org-level-4 ((,class (:foreground ,crshd2-yellow-2))))
   `(org-level-5 ((,class (:foreground ,crshd2-cyan))))
   `(org-level-6 ((,class (:foreground ,crshd2-green-1))))
   `(org-level-7 ((,class (:foreground ,crshd2-red-3))))
   `(org-level-8 ((,class (:foreground ,crshd2-blue-4))))
   `(org-link ((,class (:foreground ,crshd2-yellow-2 :underline t))))
   `(org-scheduled ((,class (:foreground ,crshd2-green+4))))
   `(org-scheduled-previously ((,class (:foreground ,crshd2-red-3))))
   `(org-scheduled-today ((,class (:foreground ,crshd2-blue+1))))
   `(org-special-keyword ((,class (:foreground ,crshd2-yellow-1))))
   `(org-table ((,class (:foreground ,crshd2-green+2))))
   `(org-tag ((,class (:bold t :weight bold))))
   `(org-time-grid ((,class (:foreground ,crshd2-orange))))
   `(org-todo ((,class (:bold t :foreground ,crshd2-red :weight bold))))
   `(org-upcoming-deadline ((,class (:inherit font-lock-keyword-face))))
   `(org-warning ((,class (:bold t :foreground ,crshd2-red :weight bold))))

   ;; outline
   `(outline-8 ((,class (:inherit default))))
   `(outline-7 ((,class (:inherit outline-8 :height 1.05))))
   `(outline-6 ((,class (:inherit outline-7 :height 1.08))))
   `(outline-5 ((,class (:inherit outline-6 :height 1.1))))
   `(outline-4 ((,class (:inherit outline-5 :height 1.13))))
   `(outline-3 ((,class (:inherit outline-4 :height 1.15))))
   `(outline-2 ((,class (:inherit outline-3 :height 1.18))))
   `(outline-1 ((,class (:inherit outline-2 :height 1.2))))

   ;; post-mode
   `(post-email-address-text-face ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(post-emoticon-face ((,class (:foreground ,crshd2-green+2 :weight bold))))
   `(post-header-keyword-face ((,class (:foreground ,crshd2-bg+1))))
   `(post-header-value-face ((,class (:foreground ,crshd2-fg))))
   `(post-multiply-quoted-text-face ((,class (:foreground ,crshd2-orange))))
   `(post-quoted-text-face ((,class (:foreground ,crshd2-yellow))))
   `(post-signature-text-face ((,class (:foreground ,crshd2-bg+2))))
   `(post-underline-face ((,class (:foreground ,crshd2-green))))
   `(post-url-face ((,class (:foreground ,crshd2-blue-2 :underline t))))

   ;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,crshd2-cyan :weight bold))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground ,crshd2-yellow :weight bold))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground ,crshd2-blue+1 :weight bold))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground ,crshd2-red+1 :weight bold))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground ,crshd2-green+1 :weight bold))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground ,crshd2-blue-1 :weight bold))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground ,crshd2-green+4 :weight bold))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground ,crshd2-red-3 :weight bold))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground ,crshd2-yellow-2 :weight bold))))
   `(rainbow-delimiters-depth-10-face ((,class (:foreground ,crshd2-green+2 :weight bold))))
   `(rainbow-delimiters-depth-11-face ((,class (:foreground ,crshd2-blue+1 :weight bold))))
   `(rainbow-delimiters-depth-12-face ((,class (:foreground ,crshd2-red-3 :weight bold))))

   ;; rpm-mode
   `(rpm-spec-dir-face ((,class (:foreground ,crshd2-green))))
   `(rpm-spec-doc-face ((,class (:foreground ,crshd2-green))))
   `(rpm-spec-ghost-face ((,class (:foreground ,crshd2-red))))))
